name: CentOS Stream

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-centos:
    name: RedHat
    permissions:
        contents: write
        packages: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container: quay.io/centos/centos:stream9
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare
        run: |
          dnf install git make cmake gcc gcc-c++ binutils glibc-devel valgrind autoconf libtool bison automake libxml2-devel sudo which rpmdevtools rpmlint yum-utils python3 -y
      - name: Configure & build & ctest & Create RPM Installer
        run: |
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release -D BUILD_TESTING=ON
            cmake --build .
            cpack --config CPackConfig.cmake -G RPM
            ctest -C Release --output-on-failure -F
