name: release

on:
  release:
    types: [published]

jobs:
  build-windows:
    name: Windows (${{ matrix.config.target }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {target: x64,     build: win64 }
          - {target: Win32,   build: win32 }
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.config.target }}
      - uses: actions/checkout@v4
      - name: Configure
        run: |
            mkdir build
            cd build
            cmake .. -D BUILD_TESTING=OFF -A ${{ matrix.config.target }}
      - name: Build
        run: |
            cd build
            cmake --build . --config Release
      - name: Create NSIS Installer from Release
        run: cpack -G NSIS Release
      - name: Upload the windows binary artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: built/Packaging/tcc-0.9.28rc-${{ matrix.config.build }}.exe
          asset_name: TinyCC-0.9.28rc_cross-compiler-${{ matrix.config.build }}.exe
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "Tiny CC Windows Installer, includes full Mingw32 headers, and cross compiling tool chains for:
                i386-linux, x86_64-linux, i386-win32, x86_64-osx, arm, arm64, riscv64, arm-wince, arm64-osx."

  build-macos:
    name: macOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Find includes
        run: |
            gcc -v -xc++ /dev/null -fsyntax-only
            sudo ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
      - name: Configure & build
        run: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release -D BUILD_TESTING=OFF ..
            cmake --build .
      - name: Create DMG Installer from Release
        run: cpack -G DMG Release
      - name: Upload the windows binary artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: built/Packaging/xxx.dmg
          asset_name: TinyCC-0.9.28rc_cross-compiler-xxx.dmg
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "Tiny CC macOS Installer, includes full Windows Mingw32 headers, and cross compiling tool chains for:
                i386-linux, x86_64-linux, i386-win32, x86_64-win64, arm, arm64, riscv64, arm-wince, arm64-osx."

  build-linux:
    name: Linux ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: amd64
            flags: -m64
        #  - target: x86
        #    flags: -m32
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -q -y
          sudo apt-get install -y gcc-multilib g++-multilib valgrind libc6-dbg libc6-dbg:i386
      - name: Configure & build
        run: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release -D BUILD_TESTING=OFF -DCMAKE_C_FLAGS=${{ matrix.flags }} ..
            cmake --build .
      - name: Create DEB Installer from Release
        run: cpack -G DEB Release
      - name: Upload the windows binary artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: built/Packaging/xxx.deb
          asset_name: TinyCC-0.9.28rc_cross-compiler-xxx.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "Tiny CC DEB Installer, includes full Windows Mingw32 headers, and cross compiling tool chains for:
                i386-linux, i386-win32, x86_64-win64, x86_64-osx, arm, arm64, riscv64, arm-wince, arm64-osx."
